CREATE DATABASE CONCINNITY;
USE CONCINNITY;

CREATE TABLE PERSONAL(
	ID  INTEGER NOT NULL,
    CI INTEGER NOT NULL,
    NOMBRE VARCHAR (50) NOT NULL,
    SEXO CHAR NOT NULL,
    TELEFONO INTEGER NOT NULL,
    CORREO VARCHAR (25),
    DOMICILIO VARCHAR (60),
    PRIMARY KEY (ID)
);

CREATE TABLE ROL(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR (20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USUARIO(
	ID INTEGER NOT NULL,
    NOMBRE_USUARIO VARCHAR (20),
    CONTRASEÑA VARCHAR (20),
    ID_ROL INTEGER NOT NULL,
	ID_PERSONAL INTEGER NOT NULL,
    PRIMARY KEY (ID),
	FOREIGN KEY(ID_ROL) REFERENCES ROL(ID),
	FOREIGN KEY(ID_PERSONAL) REFERENCES PERSONAL(ID)
);

CREATE TABLE BITACORA(
	ID INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    ACCION VARCHAR (20),
    PRIMARY  KEY (ID),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE PROVEEDOR(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR  (50) NOT NULL,
    DIRECCION VARCHAR (60),
    TELEFONO INTEGER NOT NULL,
    CORREO VARCHAR (25) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE NOTA_COMPRA(
	ID INTEGER NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    MONTO_TOTAL INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	ID_PROVEEDOR INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(ID)
);

CREATE TABLE TALLA(
	ID INTEGER NOT NULL,
    NRO_TALLA VARCHAR (3) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR (20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MATERIAL(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR (20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MARCA(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR (20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTO(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    OFERTA  DECIMAL NOT NULL,
    COSTO DECIMAL NOT NULL,
    PRECIO DECIMAL NOT NULL,
	DESCRIPCION VARCHAR (50) NOT NULL,
	STOCK INTEGER NOT NULL,
	ID_TALLA INTEGER NOT NULL,
	ID_CATEGORIA INTEGER NOT NULL,
	ID_MATERIAL INTEGER NOT NULL,
	ID_MARCA INTEGER NOT NULL,
    PRIMARY KEY (ID),
	FOREIGN KEY(ID_TALLA) REFERENCES TALLA(ID),
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID),
	FOREIGN KEY(ID_MATERIAL) REFERENCES MATERIAL(ID),
	FOREIGN KEY(ID_MARCA) REFERENCES MARCA(ID),

);

CREATE TABLE DETALLE_NOTACOMPRA(
    COSTO INTEGER NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    IMPORTE INTEGER NOT NULL,
    ID_NOTACOMPRA INTEGER NOT NULL,
    ID_PRODUCTO INTEGER NOT NULL,
    PRIMARY KEY (ID_NOTACOMPRA, ID_PRODUCTO),
	FOREIGN KEY(ID_NOTACOMPRA) REFERENCES NOTA_COMPRA(ID),
	FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID),
);

CREATE TABLE DETALLE_NOTAVENTA(
	CANTIDAD INTEGER NOT NULL,
    PRECIO INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    ID_NOTAVENTA INTEGER NOT NULL,
    ID_PRODUCTO INTEGER NOT NULL,	
    PRIMARY KEY (ID_NOTAVENTA, ID_PRODUCTO)
);

CREATE TABLE NOTA_SALIDA(
	ID INTEGER NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE DETALLE_NOTASALIDA(
	ID INTEGER NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    ID_NOTASALIDA INTEGER NOT NULL,
    ID_PRODUCTO INTEGER NOT NULL,
    PRIMARY KEY (ID)
);



CREATE TABLE NOTA_VENTA(
	ID INTEGER NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    MONTO_TOTAL INTEGER NOT NULL,
    DESCUENTO INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR (50) NOT NULL,
    TELEFONO INTEGER NOT NULL,
    CORREO VARCHAR (40),
    PRIMARY KEY (ID)
);
