USE CONCINNITY;

-- CONSULTAS GENERALES.

-- 1. Mostrar los nombres de cada personal y el rol que cumplen.

SELECT PERSONAL.NOMBRE, ROL.NOMBRE
FROM PERSONAL, USUARIO, ROL
WHERE PERSONAL.ID=USUARIO.ID_PERSONAL AND USUARIO.ID_ROL=ROL.ID
GROUP BY PERSONAL.NOMBRE, ROL.NOMBRE;
 
-- 2. Mostrar la cantidad de compras realizadas a cada proveedor.

SELECT PROVEEDOR.NOMBRE, count(ID_PROVEEDOR) AS CANT_COMPRAS
FROM PROVEEDOR, NOTA_COMPRA
WHERE PROVEEDOR.ID=NOTA_COMPRA.ID_PROVEEDOR
GROUP BY PROVEEDOR.NOMBRE;
 

-- 3. Listar los productos vendidos al cliente 1.

SELECT DISTINCT PRODUCTO.NOMBRE
FROM CLIENTE, NOTA_VENTA, DETALLE_NOTAVENTA, PRODUCTO_TALLA, PRODUCTO
WHERE CLIENTE.ID= NOTA_VENTA.ID_CLIENTE AND NOTA_VENTA.ID=DETALLE_NOTAVENTA.ID_NOTAVENTA AND DETALLE_NOTAVENTA.ID_PRODUCTO=PRODUCTO_TALLA.ID_PRODUCTO
AND PRODUCTO_TALLA.ID_PRODUCTO=PRODUCTO.ID AND CLIENTE.ID=1;
 

-- 4. Ver las compras hechas al proveedor 2.

SELECT *
FROM NOTA_COMPRA
WHERE NOTA_COMPRA.ID_PROVEEDOR IN (SELECT PROVEEDOR.ID FROM PROVEEDOR WHERE PROVEEDOR.ID=2);
 

-- INVENTARIO
-- 5. Mostrar los productos en oferta.

SELECT NOMBRE, OFERTA
FROM PRODUCTO
WHERE OFERTA is not null;
 


-- 6. Mostrar todos los nombres y precios de los productos de la categoría falda.

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO
FROM CATEGORIA, PRODUCTO 
WHERE CATEGORIA.ID=PRODUCTO.ID_CATEGORIA AND CATEGORIA.NOMBRE='Falda';
 


-- 7. Listar los PRODUCTOS disponibles de la marca 'SHEIN'.

SELECT PRODUCTO.NOMBRE,PRODUCTO.ID
FROM PRODUCTO, MARCA
WHERE PRODUCTO.ID_MARCA = MARCA.ID AND MARCA.NOMBRE = 'SHEIN';
 

-- 8. Mostrar los productos de la marca FASHION NOVA.

SELECT PRODUCTO.ID, PRODUCTO.NOMBRE
FROM MARCA, PRODUCTO
WHERE MARCA.ID=PRODUCTO.ID_MARCA AND MARCA.NOMBRE='FASHION NOVA';
 


-- 9. Listar las tallas disponibles del producto 'Body casual'.

SELECT NOMBRE_TALLA, PRODUCTO.NOMBRE
FROM TALLA, PRODUCTO, PRODUCTO_TALLA
WHERE TALLA.ID = PRODUCTO_TALLA.ID_TALLA AND PRODUCTO_TALLA.ID_PRODUCTO= PRODUCTO.ID AND PRODUCTO.NOMBRE = 'Body casual';
 


-- 10. Listar la cantidad de los productos y sus tallas disponibles de la marca 'SHEIN'.

SELECT PRODUCTO. NOMBRE, PRODUCTO_TALLA.STOCK, TALLA.NOMBRE_TALLA
FROM PRODUCTO, MARCA, PRODUCTO_TALLA, TALLA
WHERE PRODUCTO.ID_MARCA = MARCA.ID AND PRODUCTO.ID = PRODUCTO_TALLA.ID_PRODUCTO AND PRODUCTO_TALLA.ID_TALLA = TALLA.ID AND MARCA.NOMBRE = 'SHEIN';
 

-- 11. Listar los productos vendidos de talla L.

SELECT NOMBRE
FROM PRODUCTO
WHERE ID IN( SELECT ID_PRODUCTO
	FROM DETALLE_NOTAVENTA
	WHERE ID_PRODUCTO IN(SELECT ID_PRODUCTO
				FROM PRODUCTO_TALLA					
				WHERE ID_TALLA IN(SELECT ID
								FROM TALLA
								WHERE NOMBRE_TALLA = 'L')
						)
);
 

-- 12. Listar los productos comprados de talla 'S'.

SELECT NOMBRE
FROM PRODUCTO
WHERE ID IN(SELECT ID_PRODUCTO
		FROM DETALLE_NOTACOMPRA
		WHERE ID_PRODUCTO IN(SELECT ID_PRODUCTO
					FROM PRODUCTO_TALLA
					WHERE ID_TALLA IN(SELECT ID
								FROM TALLA
								WHERE NOMBRE_TALLA = 'S')
							)
);
 

--FIN INVENTARIO

-- 13. Mostrar todas las notas de ventas donde se hayan vendido los productos de material de cuero.

SELECT NOTA_VENTA.* FROM NOTA_VENTA, DETALLE_NOTAVENTA, PRODUCTO_TALLA, PRODUCTO, MATERIAL
WHERE NOTA_VENTA.ID= DETALLE_NOTAVENTA.ID_NOTAVENTA AND DETALLE_NOTAVENTA.ID_PRODUCTO=PRODUCTO_TALLA.ID_PRODUCTO 
AND PRODUCTO_TALLA.ID_PRODUCTO=PRODUCTO.ID AND PRODUCTO.ID_MATERIAL=MATERIAL.ID AND MATERIAL.NOMBRE='cuero';
 

-- 14. Listar al personal que aún no ha realizado una venta en la tienda.
SELECT *
FROM PERSONAL
WHERE PERSONAL.ID NOT IN(SELECT USUARIO.ID_PERSONAL
			FROM USUARIO, NOTA_VENTA
			WHERE USUARIO.ID=NOTA_VENTA.ID_USUARIO
); 

-- 15. Listar los productos que salieron del inventario

SELECT DISTINCT(PRODUCTO.NOMBRE)
FROM DETALLE_NOTASALIDA, PRODUCTO_TALLA, PRODUCTO
WHERE PRODUCTO.ID=PRODUCTO_TALLA.ID_PRODUCTO AND PRODUCTO_TALLA.ID_PRODUCTO=DETALLE_NOTASALIDA.ID_PRODUCTO;

-- CONSULTAS ESPECIFICAS.

-- 15. Mostar el nombre Y TELEFONO del vendedor que atendió al cliente Yuliana Rodriguez.

SELECT PERSONAL.NOMBRE, PERSONAL.TELEFONO
from  CLIENTE, NOTA_VENTA, USUARIO, PERSONAL
WHERE CLIENTE.ID = NOTA_VENTA.ID_CLIENTE
AND NOTA_VENTA.ID_USUARIO = USUARIO.ID
AND USUARIO.ID_PERSONAL = PERSONAL.ID
AND CLIENTE.NOMBRE = 'Yuliana Rodriguez';

-- 16. Mostrar la suma total del importe comprado al proveedor 2.

SELECT SUM(DETALLE_NOTACOMPRA.IMPORTE) AS SUMA_TOTAL_DEL_IMPORTE
FROM PROVEEDOR, NOTA_COMPRA, DETALLE_NOTACOMPRA
WHERE PROVEEDOR.ID=NOTA_COMPRA.ID_PROVEEDOR AND NOTA_COMPRA.ID=DETALLE_NOTACOMPRA.ID_NOTACOMPRA AND PROVEEDOR.ID=2;
 
-- 17. Listar los nombres de las personas que hicieron una compra el 20 de octubre del 2021.
SELECT CLIENTE.NOMBRE
FROM NOTA_VENTA, CLIENTE
WHERE NOTA_VENTA.ID_CLIENTE=CLIENTE.ID AND NOTA_VENTA.FECHA_HORA BETWEEN '00:00:00 20/10/2021' AND '23:59:59 20/10/2021';
 

-- 18. Listar los productos de la nota de compra que fueron ingresados desde el 01 de julio del 2021 hasta el 30 de agosto de 2021.
SELECT DISTINCT PRODUCTO.NOMBRE
FROM NOTA_COMPRA, DETALLE_NOTACOMPRA, PRODUCTO_TALLA, PRODUCTO
WHERE NOTA_COMPRA.ID=DETALLE_NOTACOMPRA.ID_NOTACOMPRA AND DETALLE_NOTACOMPRA.ID_PRODUCTO=PRODUCTO_TALLA.ID_PRODUCTO
AND PRODUCTO_TALLA.ID_PRODUCTO=PRODUCTO.ID AND NOTA_COMPRA.FECHA_HORA BETWEEN '00:00:00 01/07/2021' AND '23:59:59 07/08/2021';

-- 19. Mostrar la mínima cantidad que nos suministró el proveedor FASHION NOVA.
 SELECT MIN(DETALLE_NOTACOMPRA.CANTIDAD) AS PRODUCTOS_FASHION
 FROM PROVEEDOR, NOTA_COMPRA, DETALLE_NOTACOMPRA
 WHERE PROVEEDOR.ID=NOTA_COMPRA.ID_PROVEEDOR AND NOTA_COMPRA.ID=DETALLE_NOTACOMPRA.ID_NOTACOMPRA
  AND PROVEEDOR.NOMBRE='FASHION NOVA';
 

-- 20. Mostrar los nombres de los productos de la nota de salida de 2021/08/06.
SELECT DISTINCT PRODUCTO.NOMBRE
FROM NOTA_SALIDA, DETALLE_NOTASALIDA, PRODUCTO_TALLA, PRODUCTO
WHERE NOTA_SALIDA.ID=DETALLE_NOTASALIDA.ID_NOTASALIDA
 AND DETALLE_NOTASALIDA.ID_PRODUCTO=PRODUCTO_TALLA.ID_PRODUCTO AND PRODUCTO_TALLA.ID_PRODUCTO=PRODUCTO.ID
 AND NOTA_SALIDA.FECHA_HORA BETWEEN '00:00:00 2021/08/06' AND '23:59:59 2021/08/06'; 

-- 21. Mostrar el mayor monto total ingresado por una nota de venta.
SELECT MAX(NOTA_VENTA.MONTO_TOTAL)
FROM NOTA_VENTA;

-- 22. Mostrar cuantas compras hizo la cliente Melody Seña.

SELECT CLIENTE.NOMBRE, COUNT(*) AS CANT_COMPRAS
FROM  CLIENTE , NOTA_VENTA
WHERE CLIENTE.ID = NOTA_VENTA.ID_CLIENTE AND CLIENTE.NOMBRE = 'Melody seña'
GROUP BY CLIENTE.NOMBRE;
 
-- 23. Que productos a comprado la cliente Melody Seña.

SELECT PRODUCTO.NOMBRE
FROM CLIENTE, NOTA_VENTA, PRODUCTO, DETALLE_NOTAVENTA
WHERE CLIENTE.ID = NOTA_VENTA.ID_CLIENTE 
AND DETALLE_NOTAVENTA.ID_NOTAVENTA = NOTA_VENTA.ID
AND DETALLE_NOTAVENTA.ID_PRODUCTO = PRODUCTO.ID
AND CLIENTE.NOMBRE = 'Melody seña';

-- 24. Mostrar todos los nombres y precios de los productos de la marca coloritta y material de algodón.

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO
FROM MARCA, MATERIAL, PRODUCTO
WHERE MARCA.ID=PRODUCTO.ID_MARCA AND MATERIAL.ID=PRODUCTO.ID_MATERIAL AND MARCA.NOMBRE='coloritta'
 AND MATERIAL.NOMBRE='algodon';

-- 25. Listar los clientes que compraron productos con el monto total mayor a 200.

SELECT CLIENTE.NOMBRE
FROM CLIENTE, NOTA_VENTA
WHERE CLIENTE.ID=NOTA_VENTA.ID_CLIENTE AND NOTA_VENTA.MONTO_TOTAL>200;

-- 26. Mostrar el mínimo monto total que pagó la cliente Yuliana Rodriguez.

SELECT MIN(MONTO_TOTAL) AS MONTO_TOTAL
FROM NOTA_VENTA
WHERE NOTA_VENTA.ID_CLIENTE IN (SELECT CLIENTE.ID FROM CLIENTE WHERE CLIENTE.NOMBRE='Yuliana Rodriguez');

-- 27. Mostrar la cantidad de productos en Stock cuyo precio es de 100.

SELECT SUM(PRODUCTO_TALLA.STOCK) AS CANTIDAD
FROM PRODUCTO, PRODUCTO_TALLA
WHERE PRODUCTO.ID=PRODUCTO_TALLA.ID_PRODUCTO AND PRODUCTO.PRECIO='100';

-- 28. Mostrar la cantidad de productos de la marca Shein.

SELECT SUM(PRODUCTO_TALLA.STOCK)
FROM MARCA, PRODUCTO, PRODUCTO_TALLA
WHERE MARCA.ID=PRODUCTO.ID_MARCA AND PRODUCTO.ID =PRODUCTO_TALLA.ID_PRODUCTO AND MARCA.NOMBRE='SHEIN';

-- 29. Mostrar la cantidad de productos del material Jean.

SELECT SUM(PRODUCTO_TALLA.STOCK) AS CANTNTIDAD_JEANS
FROM MATERIAL, PRODUCTO, PRODUCTO_TALLA
WHERE MATERIAL.ID=PRODUCTO.ID_MATERIAL
 AND MATERIAL.NOMBRE='Jean'
 AND PRODUCTO.ID =PRODUCTO_TALLA.ID_PRODUCTO;
 
-- 30. Mostrar la cantidad de productos de la categoria Vestido.

SELECT SUM(PRODUCTO_TALLA.STOCK) AS CANTNTIDAD_VESTIDOS
FROM CATEGORIA, PRODUCTO, PRODUCTO_TALLA
WHERE CATEGORIA.ID=PRODUCTO.ID_CATEGORIA
AND CATEGORIA.NOMBRE='Vestido'
AND PRODUCTO.ID =PRODUCTO_TALLA.ID_PRODUCTO;
 
-- 31. Listar las personas que hicieron más de 3 compras.

SELECT CLIENTE.NOMBRE, COUNT(NOTA_VENTA.ID_CLIENTE) AS CANTIDAD_DE_COMPRAS
FROM CLIENTE, NOTA_VENTA
WHERE CLIENTE.ID=NOTA_VENTA.ID_CLIENTE
GROUP BY CLIENTE.NOMBRE
HAVING COUNT(NOTA_VENTA.ID_CLIENTE)>3;
