CREATE DATABASE CONCINNITY;
USE CONCINNITY;

CREATE TABLE PERSONAL(
	ID  INTEGER NOT NULL,
    CI INTEGER NOT NULL,
    NOMBRE VARCHAR (50) NOT NULL,
    SEXO CHAR NOT NULL,
    TELEFONO INTEGER NOT NULL,
    CORREO VARCHAR (30),
    DOMICILIO VARCHAR (60),
    PRIMARY KEY (ID)
);

CREATE TABLE ROL(
	ID VARCHAR(3) NOT NULL,
    NOMBRE VARCHAR (20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USUARIO(
	ID INTEGER NOT NULL,
    NOMBRE_USUARIO VARCHAR (20) NOT NULL,
    CONTRASEÑA VARCHAR (20) NOT NULL,
    ID_ROL VARCHAR(3) NOT NULL,
	ID_PERSONAL INTEGER NOT NULL,
    PRIMARY KEY (ID),
	FOREIGN KEY(ID_ROL) REFERENCES ROL(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	FOREIGN KEY(ID_PERSONAL) REFERENCES PERSONAL(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE BITACORA(
    ID_USUARIO INTEGER NOT NULL,
	ID INTEGER NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    ACCION VARCHAR (20),
    PRIMARY  KEY (ID, ID_USUARIO),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE PROVEEDOR(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR  (50) NOT NULL,
    DIRECCION VARCHAR (60),
    TELEFONO INTEGER NOT NULL,
    CORREO VARCHAR (30) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE NOTA_COMPRA(
	ID INTEGER NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    MONTO_TOTAL DECIMAL(8,2) NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	ID_PROVEEDOR INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE CATEGORIA(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR (20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MATERIAL(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR (20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MARCA(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR (20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TALLA(
	ID INTEGER NOT NULL,
	NOMBRE_TALLA VARCHAR(8) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE PRODUCTO(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
	PRECIO DECIMAL(6,2) NOT NULL,
    COSTO DECIMAL(6,2) NOT NULL,
	OFERTA  DECIMAL(3,2),
	DESCRIPCION VARCHAR (50) NOT NULL,
	ID_CATEGORIA INTEGER NOT NULL,
	ID_MATERIAL INTEGER NOT NULL,
	ID_MARCA INTEGER NOT NULL,
    PRIMARY KEY (ID),
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	FOREIGN KEY(ID_MATERIAL) REFERENCES MATERIAL(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	FOREIGN KEY(ID_MARCA) REFERENCES MARCA(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE PRODUCTO_TALLA
(
	ID_PRODUCTO INTEGER NOT NULL,
	ID_TALLA INTEGER NOT NULL,
	STOCK INTEGER NOT NULL,
	PRIMARY KEY(ID_PRODUCTO, ID_TALLA),
	FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	FOREIGN KEY(ID_TALLA) REFERENCES TALLA(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE DETALLE_NOTACOMPRA(
	ID_NOTACOMPRA INTEGER NOT NULL,
    ID_PRODUCTO INTEGER NOT NULL,
    ID_TALLA INTEGER NOT NULL,
    COSTO DECIMAL(6,2) NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    IMPORTE DECIMAL(7,2) NOT NULL,
    PRIMARY KEY (ID_NOTACOMPRA, ID_PRODUCTO, ID_TALLA),
	FOREIGN KEY(ID_PRODUCTO, ID_TALLA) REFERENCES PRODUCTO_TALLA(ID_PRODUCTO, ID_TALLA)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	FOREIGN KEY(ID_NOTACOMPRA) REFERENCES NOTA_COMPRA(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE NOTA_SALIDA(
	ID INTEGER NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE DETALLE_NOTASALIDA(
    ID_NOTASALIDA INTEGER NOT NULL,
    ID_PRODUCTO INTEGER NOT NULL,
	ID_TALLA INTEGER NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    PRIMARY KEY (ID_PRODUCTO, ID_TALLA, ID_NOTASALIDA),
	FOREIGN KEY(ID_PRODUCTO, ID_TALLA) REFERENCES PRODUCTO_TALLA(ID_PRODUCTO, ID_TALLA)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	FOREIGN KEY(ID_NOTASALIDA) REFERENCES NOTA_SALIDA(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE CLIENTE(
	ID INTEGER NOT NULL,
    NOMBRE VARCHAR (50) NOT NULL,
    TELEFONO INTEGER NOT NULL,
    CORREO VARCHAR (40),
    PRIMARY KEY (ID)
);

CREATE TABLE NOTA_VENTA(
	ID INTEGER NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
	MONTO_PAGO DECIMAL(8,2) NOT NULL,
    DESCUENTO DECIMAL(3,2),
	MONTO_TOTAL DECIMAL(8,2) NOT NULL,
	ID_CLIENTE INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
    PRIMARY KEY (ID),
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE DETALLE_NOTAVENTA(
	ID_NOTAVENTA INTEGER NOT NULL,
    ID_PRODUCTO INTEGER NOT NULL,
	ID_TALLA INTEGER NOT NULL,
	PRECIO DECIMAL(6,2) NOT NULL,
	CANTIDAD INTEGER NOT NULL,
	TOTAL DECIMAL(7,2) NOT NULL,
	PRIMARY KEY (ID_PRODUCTO, ID_TALLA, ID_NOTAVENTA),
	FOREIGN KEY(ID_PRODUCTO, ID_TALLA) REFERENCES PRODUCTO_TALLA(ID_PRODUCTO, ID_TALLA)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	FOREIGN KEY(ID_NOTAVENTA) REFERENCES NOTA_VENTA(ID)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);