USE CONCINITY;
-- 1. Listar de administradores que se registraron el 25 de junio
-- 2. Listar de administradores que se registraron el 25 de junio

SELECT *FROM PERSONAL;
SELECT *FROM ROL;
SELECT *FROM USUARIO;
SELECT *FROM PROVEEDOR;
SELECT *FROM NOTA_COMPRA;
SELECT *FROM CATEGORIA;
SELECT *FROM MATERIAL;
SELECT *FROM MARCA;
SELECT *FROM PRODUCTO;
SELECT *FROM DETALLE_NOTACOMPRA;